In [3]:
from src.layers import FullyConected as FC
import numpy as np

layer = FC(2, 3)
layer.weights

array([[0, 1, 2],
       [3, 4, 5]])

In [4]:
layer.bias

array([0, 1, 2])

In [15]:
input = np.arange(4).reshape(2, 2)
input[1] = input[1] * -1

In [21]:
z = np.matmul(input, layer.weights) + layer.bias
z

array([[  3,   5,   7],
       [ -9, -13, -17]])

In [22]:
a = np.maximum(0, z)
a

array([[3, 5, 7],
       [0, 0, 0]])

In [23]:
layer2 = FC(3, 5)
z2 = np.matmul(a, layer2.weights) + layer2.bias
z2

array([[ 95, 111, 127, 143, 159],
       [  0,   1,   2,   3,   4]])

In [24]:
layer2.weights

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
a2 = np.maximum(0, z2)
a2

array([[ 95, 111, 127, 143, 159],
       [  0,   1,   2,   3,   4]])

In [50]:
# equivalente a torch.gather
actions_taken = [1,2] # las acciones que se habrían elegido en el example a2[0] y el a2[1]
# selecciono los values de las acciones que se eligieron
ac = a2[np.arange(len(a2)), actions_taken]
ac

array([111,   2])

In [57]:
# Al mismo tiempo, creo una máscara con los índices que se han elegido
# Hay que guardar esta máscara como variable de clase
mask = np.zeros_like(a2)
mask[np.arange(len(a2)), actions_taken] += 1
mask

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]])

In [61]:
# Luego, al recibir las derivadas, se multiplica por esa máscara
# Sería el equivalente de la derivada de gather
a2 * mask

array([[  0, 111,   0,   0,   0],
       [  0,   0,   2,   0,   0]])